version: '3'
services:
    database:
      container_name: pg_container_apimae
      image: postgres
      restart: always
      networks:
        - default      
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: teste
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_api_mae
      image: dpage/pgadmin4
      networks:
        - default      
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"